# Локальная сеть: Docker подменяет исходный IP запроса, поэтому матчим по секрету,
# а не по IP. Сеть доверенная (LAN), но секрет ОБЯЗАТЕЛЬНО держим длинным.
client lan {
  ipaddr = 0.0.0.0/0
  secret = tRVMS6BcBqoQg1ssK-XKG6klGDsjsd5G
  nas_type = other
}
